### ISSUE TITLE
TypeError: None object cannot be quoted

### ISSUE THREAD

**Issue by sayalimore8722** [ozgur/python-linkedin#110]
When i execute the "http_api.py" i am getting the following error.The error is like this

$ python http_api.py
Server started on port: 8080
---------------------------------------
127.0.0.1 - - [17/Apr/2018 19:09:27] "GET /favicon.ico HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 36776)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "http_api.py", line 61, in do_GET
    open_new_tab(liw.authentication.authorization_url)
  File "/home/sayali/lib/python2.7/site-packages/linkedin/linkedin.py", line 101, in authorization_url
    qsl = ['%s=%s' % (quote(k), quote(v)) for k, v in qd.items()]
  File "/usr/lib/python2.7/urllib.py", line 1286, in quote
    raise TypeError('None object cannot be quoted')
TypeError: None object cannot be quoted

What is wrong here?

**Comment by SylvainBert** [comment]
Do you change API_KEY and API_SECRET variable in http_api.py?
If yes, did you think to replace `environ.get('your key') ` by `your_key`?

I think i had this problem and i solve by this changement but i'm not sure.
