### ISSUE TITLE
Failed to import, invalid syntax

### ISSUE THREAD

**Issue by charleskawczynski** [ozgur/python-linkedin#114]
Traceback (most recent call last):
  File "C:\Users\kawcz\Dropbox\PROGRAMMING\MAIN\job_search_scrape_linkedin\test.py", line 1, in <module>
    from linkedin import linkedin
  File "C:\Users\kawcz\AppData\Local\Programs\Python\Python36\lib\site-packages\linkedin\linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax

**Comment by shirishc** [comment]
Facing the same above issue !!!

**Comment by ramosjoel** [comment]
Whoops, looks like I reported this on Issue #115 but this is the same thing.  Looks like we're trying to use Python 3 with something that was written for Python 2

**Comment by admhpr** [comment]
mentioned this on #115 aswell:
`pip install --upgrade https://github.com/ozgur/python-linkedin/tarball/master`
seems to solve the issue.

**Comment by hsonetta** [comment]
@harps116 this didn't solve the issue

**Comment by luisberns** [comment]
> mentioned this on #115 aswell:
> `pip install --upgrade https://github.com/ozgur/python-linkedin/tarball/master`
> seems to solve the issue.

This helped for me and I could import the linkedin package.
