### ISSUE TITLE
Issue with http_api.py

### ISSUE THREAD

**Issue by mathisve** [ozgur/python-linkedin#127]
When running `http_api.py` its giving me this error:

```
Mathiss-iMac:match_ai mathis$ python3 http_api.py
Traceback (most recent call last):
  File "http_api.py", line 17, in <module>
    from linkedin.linkedin import LinkedInAuthentication, LinkedInApplication, PERMISSIONS
  File "/usr/local/lib/python3.7/site-packages/linkedin/linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax
```
I have looked through the previous issues and found that #86 is a similar issue. But this was in august of 2015, so I'm not sure if this has been fixed and re-appeared or if it hasn't yet.

Currently using **Python 3.7.3** with **linkedin==0.1.5**.

I hope it can get resolved. Thanks!

**Comment by luisberns** [comment]
#114 This issue has a solution to a similar err, maybe it helps, take a look

**Comment by mathisve** [comment]
Thanks! unfortunately that didn't fix my issue!

**Comment by avixp01** [comment]
Change to this -- ", error" -> "as error"
```except (requests.ConnectionError, requests.HTTPError) as error:```
