### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by Leo-g** [ozgur/python-linkedin#70]
Traceback (most recent call last):
    File "link-api.py", line 1, in <module>
    from linkedin import linkedin
    File "/home/leo_g/python-linkenin/venv/lib/python3.4/site-packages/linkedin/linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:

I get the above error during installation and while trying to execute code.

I am using python3 on centos 7,

any help is apreciated

**Comment by dgonzo** [comment]
Same here. OS X python 3.4, package mgmt via conda

**Comment by samirmrao** [comment]
I get the same error as well. Running Windows Python 3.4 via Anaconda3. Any help much appreciated here.
```
File "C:\Users\Samir\Anaconda3\lib\site-packages\linkedin\linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax
```

**Comment by melvinma** [comment]
Same here.

python: 3.4
Mac: Yosemite

Request Method:	GET
Request URL:	http://localhost:8000/
Django Version:	1.7.4
Exception Type:	SyntaxError
Exception Value:	
invalid syntax (linkedin.py, line 294)

**Comment by nachal** [comment]
I'm also getting the same issue. Any help would be appreciated.
File "c:\pythonexplorer\Python34\lib\site-packages\linkedin\linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax

**Comment by d3prof3t** [comment]
I'm also getting the same issue, please fix this man as soon as possible.
Traceback (most recent call last):
  File "http_api.py", line 1, in <module>
    from linkedin import linkedin
  File "/home/Saurabh/.virtualenvs/jobfinder/lib/python3.4/site-packages/linkedin/linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax

**Comment by foogunlana** [comment]
Also getting the same error, is there no work around for this? does it work in previous versions or something? Thanks

**Comment by DerekChia** [comment]
Traceback (most recent call last):
  File "http_api.py", line 17, in <module>
    from linkedin.linkedin import LinkedInAuthentication, LinkedInApplication, PERMISSIONS
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/linkedin/linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax

I'm getting this error too. I'm on 3.5.1

**Comment by kamalelsaaid** [comment]
the solution is just change the linkedin folder in the python package with the downloaded folder named linkedin and it will work with you

**Comment by aidiss** [comment]
File "C:\Users\admin\Anaconda3\lib\site-packages\linkedin\linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:

**Comment by arpit1997** [comment]
@Leo-G seems like a connection error. Are you connected to internet>

```
Traceback (most recent call last):
File "link-api.py", line 1, in <module>
from linkedin import linkedin
File "/home/leo_g/python-linkenin/venv/lib/python3.4/site-packages/linkedin/linkedin.py", line 294
except (requests.ConnectionError, requests.HTTPError), error:
```

**Comment by gkohnen** [comment]
Just reviving this thread...
The error has nothing to do with a connection problem (it states "invalid syntax").
The LinkedIn API only works on python 2, you have to upgrade it:
pip install --upgrade https://github.com/ozgur/python-linkedin/tarball/master

**Comment by WillZzzz** [comment]
@gkohnen Thank you so much! Nailed it with your answer.

**Comment by zhiiiyang** [comment]
@gkohnen it also solves my problem too. Thank you so much!
