### ISSUE TITLE
TypeError: None object cannot be quoted

### ISSUE THREAD

**Issue by pythonshiva** [ozgur/python-linkedin#74]
When i execute the "http_api.py" i am getting the following error.The error is like this

$ python http_api.py
Server started on port: 8080
127.0.0.1 - - [05/Feb/2015 11:56:14] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49805)
Traceback (most recent call last):
  File "D:\Python27\Lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Python27\Lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Python27\Lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "D:\Python27\Lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "D:\Python27\Lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "http_api.py", line 57, in do_GET
    print liw.authentication.authorization_url
  File "c:\Users\BITON-G510\Desktop\XMPP_ENV\lib\site-packages\linkedin\linkedin.py", line 96, in authorization_url
    qsl = ['%s=%s' % (urllib.quote(k), urllib.quote(v)) for k, v in qd.items()]
  File "D:\Python27\Lib\urllib.py", line 1269, in quote
    raise TypeError('None object cannot be quoted')
TypeError: None object cannot be quoted.

What is the mistake i am doing..?

**Comment by LuRsT** [comment]
Hi,

You are expected to provide the environment variables LINKEDIN_API_KEY and LINKEDIN_API_SECRET before running that script.
